# Generated by Django 4.0.1 on 2022-01-16 18:32

import django.core.validators
from django.db import migrations, models
import src.base.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('m', 'man'), ('w', 'woman')], max_length=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=src.base.services.get_path_upload_avatar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])])),
                ('is_staff', models.BooleanField(blank=True, default=False)),
                ('is_super_user', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
