# Generated by Django 4.0.1 on 2022-01-23 15:35

from django.db import migrations, models
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='file_name',
            field=models.FileField(default=1, upload_to=src.base.services.get_path_upload_avatar),
            preserve_default=False,
        ),
    ]
