# Generated by Django 4.0.1 on 2022-02-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_adress_user_latitude_user_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18, null=True),
        ),
    ]
