# Generated by Django 4.0.1 on 2022-02-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_latitude_alter_user_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=1, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=1, max_digits=18),
            preserve_default=False,
        ),
    ]
