# Generated by Django 4.0.1 on 2022-02-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
